"""Regenerate all figures used by the metamorphic-2 paper.

This script is the reproducible bridge from experiment CSV outputs to the
LaTeX paper image directory. It deliberately does not hand-copy PNGs: each paper
figure is regenerated by calling the plotting functions used by the experiment
scripts.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd

from budget_study import plot_budget_results
from rq2_budget_bundle_study import create_method_plots


ROOT = Path(__file__).resolve().parent
DEFAULT_PAPER_DIR = ROOT / "paper" / "ictac26"


def _parse_ints(text: str) -> tuple[int, ...]:
    return tuple(int(value.strip()) for value in text.split(",") if value.strip())


def generate_paper_figures(
    budget_runs_csv: Path,
    rq2_results_csv: Path,
    paper_dir: Path,
    budget: float,
    sizes: tuple[int, ...],
    bundle_sizes: tuple[int, ...],
) -> list[Path]:
    image_dir = paper_dir.resolve() / "images"
    image_dir.mkdir(parents=True, exist_ok=True)

    budget_results = pd.read_csv(budget_runs_csv)
    rq2_results = pd.read_csv(rq2_results_csv)

    outputs = [
        image_dir / "budget_times.png",
        image_dir / "lift_budget_times.png",
        image_dir / "av_budget_times.png",
        image_dir / "budget_runtime_only.png",
        image_dir / "lift_budget_runtime_only.png",
        image_dir / "av_budget_runtime_only.png",
    ]
    plot_budget_results(
        budget_results,
        budget,
        outputs[0],
        sizes=sizes,
    )
    plot_budget_results(
        budget_results,
        budget,
        outputs[1],
        sizes=sizes,
        case_study="lift",
    )
    plot_budget_results(
        budget_results,
        budget,
        outputs[2],
        sizes=sizes,
        case_study="av",
    )
    plot_budget_results(
        budget_results,
        budget,
        outputs[3],
        sizes=sizes,
        panels=("time",),
    )
    plot_budget_results(
        budget_results,
        budget,
        outputs[4],
        sizes=sizes,
        case_study="lift",
        panels=("time",),
    )
    plot_budget_results(
        budget_results,
        budget,
        outputs[5],
        sizes=sizes,
        case_study="av",
        panels=("time",),
    )

    create_method_plots(
        rq2_results,
        image_dir,
        budget,
        sizes=sizes,
        bundle_sizes=bundle_sizes,
    )
    outputs.extend(
        image_dir / f"lift_rq2_budget_{method}.png"
        for method in ("bfs", "approx_best_first", "nsga2", "best_first_shrink")
    )
    return outputs


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--budget-runs",
        type=Path,
        default=ROOT / "budget_results" / "budget_runs.csv",
        help="CSV produced by budget_study.py.",
    )
    parser.add_argument(
        "--rq2-results",
        type=Path,
        default=ROOT / "results" / "rq2_budget_bundle_results.csv",
        help="CSV produced by rq2_budget_bundle_study.py.",
    )
    parser.add_argument(
        "--paper-dir",
        type=Path,
        default=DEFAULT_PAPER_DIR,
        help="LaTeX paper directory containing the images/ subdirectory.",
    )
    parser.add_argument("--budget", type=float, default=2.0)
    parser.add_argument("--sizes", type=str, default="10,20,50,100")
    parser.add_argument("--bundle-sizes", type=str, default="1,2,5")
    args = parser.parse_args()

    outputs = generate_paper_figures(
        budget_runs_csv=args.budget_runs,
        rq2_results_csv=args.rq2_results,
        paper_dir=args.paper_dir,
        budget=args.budget,
        sizes=_parse_ints(args.sizes),
        bundle_sizes=_parse_ints(args.bundle_sizes),
    )
    for output in outputs:
        print(output)


if __name__ == "__main__":
    main()
